import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { managementApi } from '../../lib/api';
export function OrganizationsPage() {
    const [orgs, setOrgs] = useState([]);
    useEffect(() => {
        managementApi.get('/organizations').then(setOrgs).catch(() => { });
    }, []);
    return (_jsxs("div", { children: [_jsxs("div", { className: "mb-6 flex items-center justify-between", children: [_jsx("h2", { className: "font-heading text-3xl font-bold text-text", children: "Organizacoes" }), _jsx(Link, { to: "/admin/organizations/novo", className: "ui-btn-primary", children: "Nova Organizacao" })] }), _jsx("div", { className: "ui-table-wrap", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "ui-table-head", children: _jsxs("tr", { children: [_jsx("th", { className: "p-4 text-left", children: "Razao Social" }), _jsx("th", { className: "p-4 text-left", children: "CNPJ" }), _jsx("th", { className: "p-4 text-left", children: "Tenant" }), _jsx("th", { className: "p-4 text-left", children: "Contrato" }), _jsx("th", { className: "p-4 text-left", children: "Valor Mensal" }), _jsx("th", { className: "p-4 text-left", children: "Status" }), _jsx("th", { className: "p-4 text-left", children: "Acoes" })] }) }), _jsx("tbody", { children: orgs.map((o) => (_jsxs("tr", { className: "ui-table-row", children: [_jsx("td", { className: "p-4 text-text", children: o.razao_social }), _jsx("td", { className: "p-4 text-text-muted", children: o.cnpj ?? '-' }), _jsxs("td", { className: "p-4 text-text-muted", children: [o.tenant_nome, " (", o.cidade, "/", o.estado, ")"] }), _jsx("td", { className: "p-4", children: o.contrato_id ? (_jsx("span", { className: `rounded-full px-2 py-1 text-xs ${o.contrato_status === 'ativo' ? 'bg-success-muted text-success' :
                                                o.contrato_status === 'suspenso' ? 'bg-warning-muted text-warning' :
                                                    'bg-danger-muted text-danger'}`, children: o.contrato_status })) : (_jsx("span", { className: "text-sm text-text-muted", children: "Sem contrato" })) }), _jsx("td", { className: "p-4 text-text-muted", children: o.valor_mensal ? `R$ ${Number(o.valor_mensal).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : '-' }), _jsx("td", { className: "p-4", children: _jsx("span", { className: `rounded-full px-2 py-1 text-xs ${o.ativo ? 'bg-success-muted text-success' : 'bg-danger-muted text-danger'}`, children: o.ativo ? 'Ativa' : 'Inativa' }) }), _jsx("td", { className: "p-4", children: _jsx(Link, { to: `/admin/organizations/${o.id}`, className: "text-sm font-medium text-text hover:text-accent", children: "Ver" }) })] }, o.id))) })] }) })] }));
}
